# Site settings
title: Bootstrap Jekyll Demo
email: karim@misinc.com
description: This is the demo file for Bootstrap for Jekyll
twitter_username: @karimardalan
github_username: @misinc
# Build settings
markdown: kramdown
